import type { Metadata } from "next";
import "./globals.css";
import  Providers  from './providers';

import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import {defaultTheme} from '@pexeso/themes/defaultTheme';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <Providers>
          <ThemeProvider theme={defaultTheme}>
            <CssBaseline />
            {children}
          </ThemeProvider>
        </Providers>
    </html>
  );
}
